[build]
  publish = "public"
  functions = "functions"
  
[[redirects]]
  from = "/page"
  to = "/"
  status = 302
  
[[_redirects]]
  from = "/.netlify/functions/*"
  to = "/ext/:split"
  status = 302
  
[build.processing]
  skip_processing = false

[build.processing.js]
  bundle = true
  minify = false